config/routes.rb
Project3::Application.routes.draw do
  get "users/new"
  get "staticpages/home"
  get "staticpages/about"
  get "questions/show"
  get "exams/new"

  post "questions/mark" => 'questions#mark'
  post "questions/unmark" => 'questions#unmark'
  post "exams/complete_exam" => 'exams#complete_exam'

resources :users
resources :sessions, only: [:new, :create, :destroy]
root  'staticpages#home'

resources :exams do
    resources :questions do
    	member do 
    		put 'mark'
    		put 'unmark'
    	end
    end
end

   match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    current_exam = Exam.find(params[:exam_id])
    @marked = current_exam.marked
    @questions = current_exam.test_bank_question_ids
    @user_answers = current_exam.user_answer 
    @end_time = current_exam.timer
  end

  def show
    current_exam = Exam.find(params[:exam_id])
    @marked = current_exam.marked
    @end_time = current_exam.timer
    @user_answer_choice = current_exam.user_answer[params[:id].to_i - 1]
    
    if  params[:id].to_i.between?(1, 5)
      @exam_question_url = current_exam.test_bank_questions[params[:id].to_i - 1].question_url
      @exam_question_choices_url = current_exam.test_bank_questions[params[:id].to_i - 1].answer_choices
      # @exam_question_choices_id = @exam_question_choices_url[params[:id].to_i - 1].id.to_s 
  	 
    else  
       redirect_to exam_questions_path(params[:exam_id])
    end
  end

  def update
    exam = Exam.find(params[:exam_id])
  	
   
    if params[:choices].nil?
      exam.user_answer[params[:id].to_i - 1] = ""
      exam.save
    else
      exam.user_answer[params[:id].to_i - 1] = params[:choices]
      exam.save
    end
    if params[:submit] == 'Review'
      redirect_to exam_questions_path(params[:exam_id])
      return
    end
    
    if params[:submit] == 'Next'
      direction_id = params[:id].to_i + 1

    else
      direction_id = params[:id].to_i - 1
    end
    redirect_to exam_question_path(exam, direction_id)
  end

  def mark
    exam = Exam.find(params[:exam_id])
   
    exam.marked[params[:id].to_i - 1] = 'Yes'
    exam.save
    render text: "Successful"
  end

  def unmark
    exam = Exam.find(params[:exam_id])
   
    exam.marked[params[:id].to_i - 1] = 'No'
    exam.save
    render text: "Successful"
  end


end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_exam_header_timer.html.erb
<header>
  <div class="container">
    <nav>
      <div id='question-number-timer'>
        <% if params[:action] == 'show' %>
            <p>Question <span class="question_counter"><%=params[:id] %></span> of 30 </p>
        <% else %>
            <p><span class="question_counter"></span> CBT Exam 1 </p>
        <% end %>
      <div id='timer'><span id="timer"></span>
      </div>
    </nav>
  </div>
</header>

<script type='text/javascript'>

  var count= <%= @end_time - Time.now %>;
  var counter=setInterval(timer, 1000);

  function timer()
  {
    console.log('called')
    count=count-1;
    
    if (count <= 0)
      {
       clearInterval(counter);
       return;
      }

    var hours = Math.floor(count/3600)
    var minutes =  Math.floor(count/60) - (hours*60);
    var seconds = count - (minutes * 60) - (hours*3600);
        
    document.getElementById("timer").innerHTML= hours + ':' + minutes + ":" + Math.ceil(seconds); 
  }

</script>

app/views/questions/_footer.html.erb
<div class="footer1">
  <div class="footer-content" align="center">
        
      <input class='direction-btn' id='back-btn' type='submit'  name='submit' value='Back' form='myform'>
      <input class='direction-btn' id='next-btn' type='submit' name='submit' value='Next' form='myform' >

     <input class='direction-btn mark'  id='mark-btn' type='submit' name='submit' <%= @marked[params[:id].to_i - 1] == 'Yes' ? "value=Marked"  : "value=Mark" %> >

      <input class='direction-btn' id='next-btn'   type='submit' name='submit' value='Review' form='myform' >
        
  </div>
</div>

app/views/questions/index.html.erb
<%= render 'exam_header_timer' %>

<table cellspacing='0' style='margin-top: 100px' style='margin:auto'> <!-- cellspacing='0' is important, must stay -->
	<!-- Table Header -->
	<thead>
		<tr>
			<th>Questions</th>
			<th>Marked</th>
			<th>Complete</th>
		</tr>
	</thead>
	<!-- Table Body -->
	<tbody>	
	<%i = 1 %>
	<% while (i < @questions.length + 1) %>
		<tr>
			<td>
				<%=link_to "Question #{i}", exam_question_path(params[:exam_id], i ) %>
			</td>
			<td> 
				<%=  @marked[i - 1] == 'Yes' ? 'Yes' : '' %>
			</td>
			<% if @user_answers[i-1].empty?  %>
			<td>
				No
			</td>
			<% else %>
			<td>
				Yes
			</td>
			<% end %>
		</tr>
			<% i += 1%>
		<% end %>
	</tbody>
</table>


<input class='direction-btn' id='next-btn'  type='submit' name='submit' value='Review incomplete' form='mark-form' >
<input class='direction-btn' id='next-btn'  type='submit' name='submit' value='Review Marked' form='mark-form' >


<%= button_to 'End Exam', exams_complete_exam_path(params[:exam_id]), :method => "post", :class =>'direction-btn', :id =>'next-btn', :style=> 'margin-left: 615px'  %>

app/views/questions/show.html.erb
<%= render 'exam_header_timer' %>

<div id='question'>
<img src=<%= @exam_question_url %> style='width:45%;' alt="some_text">

<div id='choices'><br><br>

  <%= form_tag({controller: 'questions', action: 'update'}, method: 'put', id:'myform') do %>

  <input type="radio" name="choices" class="choices" value="<%= @exam_question_choices_url.first.id %>"  <%= "checked='checked'" if @user_answer_choice == @exam_question_choices_url.first.id.to_s %> >
         A.   <img src=<%= @exam_question_choices_url.first.choice_url %>   alt="some_text"><br/>
   
    <input type="radio" name="choices" class="choices" value="<%= @exam_question_choices_url.second.id %>" <%= "checked='checked'" if @user_answer_choice == @exam_question_choices_url.second.id.to_s %>>
         B.   <img src=<%= @exam_question_choices_url.second.choice_url %>    alt="some_text"> <br/>
  
    <input type="radio" name="choices" class="choices" value="<%= @exam_question_choices_url.third.id %>" <%= "checked='checked'" if @user_answer_choice == @exam_question_choices_url.third.id.to_s %>>  
         C.   <img src=<%= @exam_question_choices_url.third.choice_url %>   alt="some_text"> <br/>
  
     <input type="radio" name="choices" class="choices" value="<%= @exam_question_choices_url.fourth.id %>" <%= "checked='checked'" if @user_answer_choice == @exam_question_choices_url.fourth.id.to_s %>>  
         D.   <img src=<%= @exam_question_choices_url.fourth.choice_url %>   alt="some_text"> <br/>
    
    <input type="radio" name="choices" class="choices" value="<%= @exam_question_choices_url.fifth.id %>" <%= "checked='checked'" if @user_answer_choice == @exam_question_choices_url.fifth.id.to_s %>>   
         E.   <img src=<%= @exam_question_choices_url.fifth.choice_url %>   alt="some_text">
   
  <% end %>
</div>

</div> 

<%= render 'footer' %>

<script type='text/javascript'>

  $(document).ready(function() {

    $(document).on('click', '#mark-btn', function () {
        $.ajax({
            type: 'PUT',
            url: '<%= mark_exam_question_path(params[:exam_id], params[:id])%>'
        }).done(function (msg) {

            $("#mark-btn").val("Marked");
            $("#mark-btn").attr("id", 'unmark-btn')
            return false
        });

    });



    $(document).on('click', "#unmark-btn", function (){
        $.ajax({
            type: 'PUT',
            url: '<%= unmark_exam_question_path(params[:exam_id], params[:id])%>'
        }).done(function (msg) {

            $("#unmark-btn").val("Mark");
            $("#unmark-btn").attr("id", 'mark-btn');
            return false
        });
    });

  
 
   });


 </script>