config/routes.rb
Project3::Application.routes.draw do
  get "users/new"
  get "staticpages/home"
  get "staticpages/about"
  get "questions/show"
  get "exams/new"

  post "questions/mark" => 'questions#mark'
  post "questions/unmark" => 'questions#unmark'
  post "exams/complete_exam" => 'exams#complete_exam'

resources :users
resources :sessions, only: [:new, :create, :destroy]
root  'staticpages#home'

resources :exams do
    resources :questions do
    	member do 
    		put 'mark'
    		put 'unmark'
    	end
    end
end

   match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

app/models/user.rb
class User
  
  include ActiveModel::SecurePassword
  include Mongoid::Document
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
 

  field :name,            type: String 
  field :email,           type: String 
  field :password_digest, type: String
  field :remember_token,  type: String
  
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :exams
#password_digest
has_secure_password


#attr_accessible :email, :password, :password_confirmation
def User.find_by_email(email)
  where(:email => email).first
end

def User.new_remember_token
  SecureRandom.urlsafe_base64  #creates a random token
end

def User.encrypt(token)
  Digest::SHA1.hexdigest(token.to_s) #this will run on everypage for a signed in user
end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token) #generates an ecrypt token to store in database
    end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@user = User.find(params[:id])
  end
  def show
  	@user = User.find(params[:id])
    @exams = current_user.exams
    puts_money
    puts @exams

  end

  def new
  	@user = User.new
  end
  
  def create 
  	@user = User.new(user_params)
  	if @user.save
  		sign_in @user
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/index.html.erb
<%= @user %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %><br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<div class='main-container'

<div class='side-bar'>
	<div class="circle">
  		<%= gravatar_for @user %>
  	</div>
    	<h1> <%= @user.name %></h1>
  
		<%= button_to 'Start new exam', exams_path, class: "btn-primary btn-large no-dblclick" %>
</div>
</div>
	
	<ul>		
		<% @exams.each do |exam| %>

		<li class="banner">
			<%= button_to 'Exam ', exam_path( exam.id), :method => "get", :class =>'btn-primary btn-large no-dblclick' %>
			<span id="start-time"><%= exam.start_time.strftime("%a %b %e %Y %T") %></span>
		<li>
			<%= link_to 'Delete', exam_path(exam.id), method: 'delete', data: { confirm: 'Are you sure?' }%>
	 <br><br><br><br>
		<% end  %>
	<ul>

		